---

spring:
  banner:
    image:
      location: classpath:banner.gif
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
debug: true
user:
  tier:
    My-tier
    My-Second-Tier
  role:
    Developer
    User